### ISSUE TITLE
Ruby 3 incompatibility calling release_groups?

### ISSUE THREAD

**Issue by gabriel** [inkstak/musicbrainz#12]
When calling `release_groups`:

```ruby
client = MusicBrainz::Client.new
albums = client.release_groups(artist: "2921ca1d-206e-411a-8d2e-e12494dcfa9a", includes: "genres")
```

```
ArgumentError: wrong number of arguments (given 3, expected 2)
/Users/gabe/.rvm/gems/ruby-3.0.2/bundler/gems/musicbrainz-8676f0dab605/lib/musicbrainz/client.rb:66:in `lookup'
/Users/gabe/.rvm/gems/ruby-3.0.2/bundler/gems/musicbrainz-8676f0dab605/lib/musicbrainz/client.rb:35:in `block (2 levels) in <class:Client>'
```

It works if I monkey patch it be explicitly defined:

```ruby
module MusicBrainz
  class Client
    def release_group(uid, **options)
      lookup("release-group", uid, **options) do |json|
        MusicBrainz::ReleaseGroup.new json
      end
    end
  end
end
```

Is this because of change in ruby 3 related to positional and keyword arguments? https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by inkstak** [comment]
The issue was already fixed in main branch but never released as a gem.
I'll publish the new release today

**Comment by inkstak** [comment]
1.2.0 released
